name: Fetch Cloudflare IPs Every 3 Hours  # 每天中午12点运行

on:
  schedule:
   - cron: '0 12 * * *'  # 每天中午12点运行  # 时间修改：从 '50 */2 * * *' 改为 '0 */3 * * *'
  workflow_dispatch:        # 允许手动触发
  push:                     # 代码推送时也运行

jobs:
  fetch-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install requests
      run: pip install requests

    - name: Run IP fetcher
      run: python test_cloudflare_ips.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ip.txt
        git diff --staged --quiet || git commit -m "Update IPs - $(date +'%Y-%m-%d %H:%M:%S')"
        git push

    - name: Wait 3 minutes before triggering DNS update  # 新增：等待3分钟步骤
      if: success()
      run: |
        echo "等待3分钟后触发DNS更新..."
        sleep 180  # 180秒 = 3分钟  # 新增：3分钟延迟
      shell: bash

    - name: Trigger DNS update workflow  # 新增：触发DNS更新工作流
      if: success()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'update-dns.yml',
            ref: 'main'
          })
